export const SUBJECT = [
  { key: "Chào cờ", value: 1 },
  { key: "Toán học", value: 2 },
  { key: "Vật lý", value: 3 },
  { key: "Hóa học", value: 4 },
  { key: "Sinh học", value: 5 },
  { key: "Ngữ văn", value: 6 },
  { key: "Lịch sử", value: 7 },
  { key: "Địa lý", value: 8 },
  { key: "Tin học", value: 9 },
  { key: "Âm nhạc", value: 10 },
  { key: "Mỹ thuật", value: 11 },
  { key: "Tự nhiên xã hội", value: 12 },
  { key: "Công nghệ", value: 13 },
  { key: "Đạo đức", value: 14 },
  { key: "Khoa học", value: 15 },
  { key: "Thủ công", value: 16 },
  { key: "Kỹ thuật", value: 17 },
  { key: "Tạo hình", value: 18 },
  { key: "Tổ hợp môn Khoa học xã hội", value: 19 },
  { key: "Khoa học tự nhiên", value: 20 },
  { key: "Tiếng Việt", value: 21 },
  { key: "Tiếng Anh", value: 22 },
  { key: "Tiếng Pháp", value: 23 },
  { key: "Tiếng Trung", value: 24 },
  { key: "Tiếng Nhật", value: 25 },
  { key: "Tiếng Hàn", value: 26 },
  { key: "Tiếng dân tộc thiểu số", value: 27 },
  { key: "Thể dục", value: 28 },
  { key: "Giáo dục quốc phòng", value: 29 },
  { key: "Giáo dục thể chất", value: 30 },
  { key: "Giáo dục ngoài giờ", value: 31 },
  { key: "Giáo dục Kinh tế và pháp luật", value: 32 },
  { key: "Giáo dục địa phương", value: 33 },
  { key: "Giáo dục công dân", value: 34 },
  { key: "Kỹ năng sống", value: 35 },
  { key: "Hoạt động trải nghiệm", value: 36 },
  { key: "Hướng nghiệp", value: 37 },
  { key: "Sinh hoạt lớp", value: 38 },
  { key: "Chữ cái", value: 39 },
  { key: "Khám phá", value: 40 },
  { key: "Cảm xúc", value: 41 },
  { key: "Giá trị sống", value: 42 },
]